# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: './dartboard-api/*/*.*.Test.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: Docker@2
  displayName: Docker Login
  inputs:
    command: 'login'
    containerRegistry: dockerhub

- task: Docker@2
  displayName: Docker Build and Push API
  inputs:
    repository: 'bryht/dartboardapi'
    command: 'buildAndPush'
    Dockerfile: './dartboard-api/DartBoard.Api/Dockerfile'
    buildContext: 'dartboard-api'
    tags: 'dev'

- task: Docker@2
  displayName: Docker Build and Push Dart WEB
  inputs:
    repository: 'bryht/dartboardweb'
    command: 'buildAndPush'
    Dockerfile: './dartboard-web/Dockerfile'
    buildContext: 'dartboard-web'
    tags: 'dev'

- task: Docker@2
  displayName: Docker Build and Push Movie WEB
  inputs:
    repository: 'bryht/movieweb'
    command: 'buildAndPush'
    Dockerfile: './movie-web/Dockerfile'
    buildContext: 'movie-web'
    tags: 'dev'
