# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: './src/DartBoardApi.sln'
    feedsToUse: 'select'
    versioningScheme: 'off'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: './src/**/*.Test.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: false
    feedsToUse: 'select'
    projects: './src/DartBoardApi/DartBoardApi.csproj'
    versioningScheme: 'off'
    arguments: '--configuration $(buildConfiguration) --output $(System.DefaultWorkingDirectory)/src/publish'

# - task: Docker@2
#   displayName: 'Build Docker'
#   inputs:
#     repository: bryht/dartboardapi
#     command: 'build'
#     Dockerfile: './src/DartBoardApi/Dockerfile'
#     buildContext: 'src'
- task: Docker@2
  displayName: Docker Login
  inputs:
    command: 'login'
    containerRegistry: dockerhub

- task: Docker@2
  inputs:
    repository: 'bryht/dartboardapi'
    command: 'buildAndPush'
    Dockerfile: './src/DartBoardApi/Dockerfile'
    buildContext: 'src'
    tags: 'api'
