# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: './DartBoardApi/DartBoardApi.sln'
    feedsToUse: 'select'
    versioningScheme: 'off'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: './**/**/*.Test.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: Docker@2
  displayName: 'Build Docker'
  inputs:
    command: 'build'
    Dockerfile: './DartBoardApi/DartBoardApi/Dockerfile'
