version: '3.4'

services:
  dartboardapi:
    image: bryht/dartboardapi:dev
    ports:
     - "8080:80"
    volumes: 
     - "./data/dartboard.db:/app/dartboard.db"
    networks:
     - private-network
  dartboardweb:
    image: bryht/dartboardweb:dev
    ports:
     - "80:3000"
    networks:
     - private-network
networks:
  private-network:
    driver: bridge
    attachable: true
