version: '3.4'

services:
  # nginx:
  #   image: nginx:1.15-alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./data/nginx:/etc/nginx/conf.d
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  #   networks:
  #    - private-network
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  dartboardapi:
    image: bryht/dartboardapi:dev
    ports:
     - "8080:80"
    volumes: 
     - ./data/dartboard.db:/app/dartboard.db
    networks:
     - private-network
  dartboardweb:
    image: bryht/dartboardweb:dev
    ports:
     - "8081:3000"
    networks:
     - private-network
  movieweb:
    image: bryht/movieweb:dev
    ports:
     - "8082:3000"
    networks:
     - private-network
networks:
  private-network:
    driver: bridge
    attachable: true
