version: '3.4'

services:
  dartboardapi:
    image: bryht/dartboardapi:dev
    ports:
     - "8080:80"
    networks:
     - private-network

networks:
  private-network:
    driver: bridge
    attachable: true