version: '3.4'

services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    networks:
     - private-network
  certbot:
    image: certbot/certbot
    networks:
     - private-network
  dartboardapi:
    image: bryht/dartboardapi:dev
    ports:
     - "8080:80"
    volumes: 
     - "./data/dartboard.db:/app/dartboard.db"
    networks:
     - private-network
  dartboardweb:
    image: bryht/dartboardweb:dev
    ports:
     - "8081:3000"
    networks:
     - private-network
  movieweb:
    image: bryht/dartboardweb:dev
    ports:
     - "8082:3000"
    networks:
     - private-network
networks:
  private-network:
    driver: bridge
    attachable: true
